# Generated by Django 5.0.6 on 2024-08-09 17:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_python', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonmodel',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
